version: '3.9'

services:
  chirps-db:
    image: postgres
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
  migration:
    build: ./chirpies
    command: python ./chirpies/manage.py migrate --noinput
    volumes:
      - .:/usr/src/app
    depends_on:
      - chirps-db
  web:
    build: ./chirpies
    command: bash -c "python ./chirpies/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - migration
      - chirps-db

volumes:
  postgres_data: